### ISSUE TITLE
Bound parameter error when joining polymorphic relations

### ISSUE THREAD

**Issue by kenaniah** [camertron/arel-helpers#20]
Given Rails 4.2.x (not sure if version matters):

```ruby
class CardLocation < ActiveRecord::Base
  belongs_to :location
  belongs_to :card, polymorphic: true
end
class Location < ActiveRecord::Base
  has_many :card_locations
  has_many :community_tickets, through: :card_locations, source: :card, source_type: "CommunityTicket"
end
class CommunityTicket < ActiveRecord::Base
  has_many :card_locations, as: :card, source_type: 'CommunityTicket'
  has_many :locations, through: :card_locations
end
```

When executing:
```ruby
Location.joins(
  ArelHelpers.join_association(Location, :community_tickets)
).to_sql
```

The output will be (`card_type` is not bound):
```sql
SELECT "locations".* 
FROM "locations" 
INNER JOIN "card_locations" ON "card_locations"."location_id" = "locations"."id" AND "card_locations"."card_type" =  
INNER JOIN "community_tickets" ON "community_tickets"."id" = "card_locations"."card_id"
```

Expected output (`..._type` is bound from the association's value of `source_type`:
```sql
SELECT "locations".* 
FROM "locations" 
INNER JOIN "card_locations" ON "card_locations"."location_id" = "locations"."id" AND "card_locations"."card_type" = 'CommunityTicket'
INNER JOIN "community_tickets" ON "community_tickets"."id" = "card_locations"."card_id"
```

The problem appears to be that the resulting query generates a parameter slot that is not satisfied in the call to `join_association` when polymorphic associations are in play. This becomes apparent when mixed in to another query that uses parameters, as the "card_type" value is filled in with a parameter from the outside query.

I'm guessing that `source_type` needs to be pulled and bound from the association's reflection, but I'm not sure where to do this.

**Comment by camertron** [comment]
Hey @kenaniah, thanks for the bug report. It looks like polymorphic "through" associations only fail with Rails 4.2 (see this [build matrix](https://travis-ci.org/camertron/arel-helpers/builds/99325321)). Such is the joy and privilege of using private APIs :grimacing:. I've created a branch (polymorphic_through) that contains a test case for the issue. I'll look into a fix.

**Comment by camertron** [comment]
Would you mind taking a look at #21 @kenaniah to see if it addresses your issue?

**Comment by kenaniah** [comment]
#21 works perfectly for me. Thanks for the supremely quick turnaround!
