### ISSUE TITLE
Nested Outer Joins Supported?

### ISSUE THREAD

**Issue by gamov** [camertron/arel-helpers#27]
Is it possible to write nested outer joins? Eg:

     PurchaseOrder.joins(:purchased_items => {:shipping_items => :shipment})

I would like the joins between purchased_items => shipping_items and shipping_items => :shipment to be outer joins.
I tried a few things without success.

**Comment by camertron** [comment]
Hey @gamov, this should be possible. Try passing the nested hash as the second argument to `#join_association`, i.e.:

```ruby
PurchaseOrder.joins(
  ArelHelpers.join_association(PurchaseOrder, purchased_items: { shipping_items: :shipment }, Arel::Nodes::OuterJoin)
)
```

The general rule of thumb is that anything you can pass to `#joins` you can also pass to `#join_association`'s second argument. I'll add a few tests and an example to the README.

**Comment by gamov** [comment]
Duh!!! I didn't think of this one, sorry! 

Yes, I need to keep in mind that rule. 

I'm in the process of removing [Squeel](https://github.com/activerecord-hackery/squeel) from a big application.
I noticed that area-helpers outer joins sometimes don't play well with [Ransack](https://github.com/activerecord-hackery/ransack). I'll investigate further.
