### ISSUE TITLE
Support for Rails 5.2

### ISSUE THREAD

**Issue by rhymes** [camertron/arel-helpers#34]
Apparently Rails 5.2 changed its internal "join dependency" structure quite a lot and the library doesn't work with it.

I've managed to track the issue from https://github.com/camertron/arel-helpers/blob/master/lib/arel-helpers/join_association.rb#L22 which calls https://github.com/camertron/arel-helpers/blob/master/lib/arel-helpers/join_association.rb#L88 (`ActiveRecord::Associations::JoinDependency.new(table, associations, [])`).

The signature of that method changed quite a bit in Rails 5.2: https://github.com/rails/rails/blob/v5.2.0/activerecord/lib/active_record/associations/join_dependency.rb#L91

unfortunately it's not well documented.

It seems they've introduced a new argument in this commit https://github.com/rails/rails/commit/ea09bf5419ec752dd020d26b03533afa457d09d6 and the concept of alias tracker

**Comment by camertron** [comment]
Ok, I was able to figure this out pretty painlessly tonight. Published as v2.7.0.

**Comment by rhymes** [comment]
Amazing, thank you @camertron !
