### ISSUE TITLE
Using CONCAT_WS

### ISSUE THREAD

**Issue by LucasCioffi** [camertron/arel-helpers#39]
Hi all, this is an impressive gem.

Can you search multiple columns at the same time?  For example, I'd like to search "John Smith" but I currently have to split the search parameter into two words and perform one search against `first_name` and one search against `last_name` (example below).

Using the Rails console, I see it's possible to use Postgres to search concatenated fields where "John Smith" will return a result:
`User.where("CONCAT_WS(' ', first_name, last_name) LIKE ?", "%#{search_phrase}%")`.

Does anyone know how to transform the line above so that it can fit as an `OR` clause below?
```
arel_query = query.joins(
    ArelHelpers.join_association(@klass, :comments)
  ).joins(
    ArelHelpers.join_association(@klass, :user)
  ).where(
    Post[:title].matches("%#{search_phrase}%")
    .or(Comment[:body].matches("%#{search_phrase}%"))
    # .or(User[:first_name].matches("%#{search_phrase.split(' ')[0]}%"))
    # .or(User[:last_name].matches("%#{search_phrase.split(' ')[-1]}%"))
  )
```

**Comment by camertron** [comment]
Hey @LucasCioffi,

Interesting question! In essence it sounds like what you're trying to do is call a SQL function. Arel does provide a (fairly verbose) way of doing so. For example:

```ruby
query.joins(
  ArelHelpers.join_association(@klass, :comments)
).joins(
  ArelHelpers.join_association(@klass, :user)
).where(
  Post[:title].matches("%#{search_phrase}%").or(
    Arel::Nodes::NamedFunction.new(
      'CONCAT_WS', [
        ' ', User[:first_name], User[:last_name]
      ]
    ).matches(
      "%#{search_phrase}%")
    )
  )
)
```
Let me know if that works :)

Also, I'm not sure you need to use `join_association` since it doesn't appear you're adding any additional join conditions or performing an outer join. The active_record API is actually really nice when you don't need any extra customization, eg:

```ruby
query.joins(comments: { user: :posts }).where(...)
```

**Comment by LucasCioffi** [comment]
@camertron thank you very much for this through explanation!

**Comment by LucasCioffi** [comment]
FYI @camertron I had to replace the empty string with a SqlLiteral like this:
`'CONCAT_WS', [Arel::Nodes::SqlLiteral.new('\' \''), V1::User[:first_name], V1::User[:last_name]]` 
to get past this error:
`Arel::Visitors::UnsupportedVisitError: Unsupported argument type: String. Construct an Arel node instead.`
Thank you, once again.

**Comment by camertron** [comment]
@LucasCioffi ah that makes sense. Thanks!
