### ISSUE TITLE
Rails 6 compatibility ? 

### ISSUE THREAD

**Issue by MatthiasRMS** [camertron/arel-helpers#40]
Hi,

I use a gem which relies on arel-helpers, so I can't update my app to Rails 6+.
Have you planned on upgrading it to support Rails 6/AR 6 ? 

If you already know what could cause issues, I'd be happy to look at it and submit a PR.

Matthias

**Comment by camertron** [comment]
Hey @MatthiasRMS,

Rails 6 support hasn't been on my todo list, but it's definitely going to need to be done at some point. I just did some real quick hacking to see if I could get tests to pass with Rails 6 and it actually worked without too many changes. Check out the `rails6` branch and see if it works for your use case.

I'm a little hesitant to publish a new version of the gem with official Rails 6 support considering it's still in beta, but I could be persuaded.

**Comment by MatthiasRMS** [comment]
Wow great thanks for being so quick to answer.
I'll try it and let you know! thanks

**Comment by michaelherold** [comment]
For what it's worth, we're using the `rails6` branch and everything is copasetic. Thanks for making that available!

**Comment by camertron** [comment]
Awesome, thank you :) Just published as v2.9.0.
