### ISSUE TITLE
test.log in published gem file

### ISSUE THREAD

**Issue by fschwahn** [camertron/arel-helpers#48]
Looking at https://my.diffend.io/gems/arel-helpers/2.12.1/2.13.0 I saw that a test log file is accidentally getting published with every release. The gemspec `files`-directive should be updated to exclude such files.

**Comment by camertron** [comment]
Hey @fschwahn, thanks for pointing this out :) Should be fixed in https://github.com/camertron/arel-helpers/commit/ee5fab2dd1a6fd24fb4d8a238060c0f6eee51367
